name: Run E2E Tests

on:
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13

      - name: Install dependencies
        run: npm ci

      - name: Start Docker Compose services
        run: docker-compose up -d

      - name: Wait for services to start
        run: sleep 20

      - name: Run E2E tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npm run test:e2e

      - name: Stop Docker Compose services
        run: docker-compose down